### ISSUE TITLE
SheetViewport isn't importable in the latest version 0.10.2

### ISSUE THREAD

**Issue by andcea** [fujidaiti/smooth_sheets#291]
I noticed `SheetViewport` was made public in recent commits however, those haven't been published as a new version yet.

When following the examples (for example [declarative_navigation_sheet.dart](https://github.com/fujidaiti/smooth_sheets/blob/main/example/lib/tutorial/declarative_navigation_sheet.dart ) or [ai_playlist_generator.dart](https://github.com/fujidaiti/smooth_sheets/blob/main/example/lib/showcase/ai_playlist_generator.dart)) `SheetViewport` is used and it won't work with the latest version of the library.

You can get it working by changing your pubspec.yaml to:
```yaml
  smooth_sheets:
    git:
      url: https://github.com/fujidaiti/smooth_sheets.git
      ref: 5fad0b8bab04fe88cc08d5c43e9d7edd1efa95be
```

but publishing a new library version would be great.
